backend:
  name: github
  repo: JamalChoudhuri/Prime-Stock
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "photos"
    label: "Prime Stock Photos"
    folder: "images"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
